version: "3"
services:
  app:
    container_name: mypan
    restart: always
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8001"
    volumes:
      - .:/mypan
    ports:
      - "8001:8001"
